# Generated by Django 3.1.7 on 2021-04-07 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('category_order', models.IntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('material', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('packaging', models.CharField(max_length=10)),
                ('hpis_code', models.CharField(max_length=20)),
                ('hc_provider', models.BooleanField(default=True)),
                ('latex_free', models.BooleanField(default=True)),
                ('med_route', models.CharField(max_length=20)),
                ('is_visible', models.BooleanField(default=True)),
                ('shop_order', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_pharma.category')),
            ],
        ),
    ]
