# Generated by Django 3.1.7 on 2021-04-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pharma', '0002_auto_20210407_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_full',
            field=models.ImageField(blank=True, height_field=1116, upload_to='products/full/%Y/%m/%d', width_field=543),
        ),
        migrations.AddField(
            model_name='product',
            name='image_small',
            field=models.ImageField(blank=True, height_field=370, upload_to='products/small/%Y/%m/%d', width_field=270),
        ),
    ]
