# Generated by Django 3.1.7 on 2021-04-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pharma', '0007_aboutus_address_phone_rate_specoffer_testimonials_welcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
