# Generated by Django 3.1.7 on 2021-04-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pharma', '0009_auto_20210408_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
