# Generated by Django 3.1.7 on 2021-04-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pharma', '0010_auto_20210408_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecOfferGreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
                ('desc', models.CharField(default='SOME STRING', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecOfferYellow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
                ('desc', models.CharField(default='SOME STRING', max_length=200, unique=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='SpecOffer',
            new_name='SpecOfferBlue',
        ),
    ]
