# Generated by Django 3.1.7 on 2021-04-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pharma', '0013_auto_20210409_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('photo', models.ImageField(upload_to='history/%Y/%m/%d')),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, unique=True)),
                ('desc', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('position', models.CharField(max_length=20)),
                ('desc', models.CharField(default='SOME STRING', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='testimonials/%Y/%m/%d')),
            ],
        ),
    ]
