# Generated by Django 3.1.7 on 2021-04-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pharma', '0014_history_ouroffer_ourteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='image',
            field=models.ImageField(blank=True, upload_to='team/%Y/%m/%d'),
        ),
    ]
