# Generated by Django 3.1.7 on 2021-04-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pharma', '0016_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_name',
        ),
        migrations.AddField(
            model_name='message',
            name='user_fname',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='message',
            name='user_lname',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='message',
            name='user_subject',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_processed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_message',
            field=models.TextField(blank=True),
        ),
    ]
