# Generated by Django 3.1.7 on 2021-04-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pharma', '0018_auto_20210419_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hc_provider',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_popular',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='latex_free',
            field=models.BooleanField(),
        ),
    ]
