# Generated by Django 3.1.7 on 2021-04-26 18:31

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main_pharma', '0021_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='photo',
            field=models.ImageField(upload_to='static/history/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/team/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_full',
            field=models.ImageField(blank=True, upload_to='static/products/full/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=0, size=[270, 370], upload_to='static/products/small/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/testimonials/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='photo',
            field=models.ImageField(upload_to='static/welcome/%Y/%m/%d'),
        ),
    ]
