# Generated by Django 3.1.7 on 2021-05-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_pharma', '0022_auto_20210426_2131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
        migrations.AlterField(
            model_name='rate',
            name='photo',
            field=models.ImageField(upload_to='static/rate/%Y/%m/%d'),
        ),
    ]
